Controllers/BooksController.cs
using LibraryApi.Data;
using LibraryApi.Models;
using LibraryApi.Models.VIewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryApi.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryContext _context;
        public BooksController(LibraryContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var books = _context.Books.Where(c => c.Count > 0);

            if (books != null)
            {
                return View(await books.ToListAsync());
            }

            return View(new List<Book>());
        }
        public async Task<IActionResult> IssuedBooks()
        {
            var issues = _context.BookIssues.Where(c => c.ReturnDate == null);
            var list = new List<GivingBookViewModel>();
            if (issues == null)
            {
                return View(list);
            }

            foreach (var issue in issues)
            {
                Reader reader = await _context.Readers.FirstOrDefaultAsync(c => c.Id == issue.ReaderId);
                Book book = await _context.Books.FirstOrDefaultAsync(c => c.Id == issue.BookID);
                list.Add(new GivingBookViewModel(book, reader));
            }

            return View(list);
        }
        public IActionResult AddBook()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddBook([Bind("Name,Author,ReleaseDate")] Book book)
        {
            if (ModelState.IsValid)
            {
                var dbBook = _context.Books.FirstOrDefault(c => c.Name == book.Name && c.Author == book.Author);
                if (dbBook == null)
                {
                    _context.Books.Add(book);
                }
                else
                {
                    dbBook.Count++;
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteBook(int id)
        {
            var book = _context.Books.FirstOrDefault(c => c.Id == id);
            if (book != null)
            {
                book.Count--;
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var book = await _context.Books.FirstOrDefaultAsync(c => c.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Author,ReleaseDate")] Book book)
        {
            if (ModelState.IsValid)
            {
                var dbBook = _context.Books.FirstOrDefault(c => c.Id == id);
                dbBook.Name = book.Name;
                dbBook.Author = book.Author;
                dbBook.ReleaseDate = book.ReleaseDate;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }
        public async Task<IActionResult> ReturnBook(int id)
        {
            var dbBook = _context.Books.FirstOrDefault(c => c.Id == id);
            dbBook.Count++;
            var issue = await _context.BookIssues.FirstOrDefaultAsync(c => c.BookID == id
            && c.ReturnDate == null);
            issue.ReturnDate = DateTime.Now;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(IssuedBooks));
        }
        public async Task<IActionResult> GiveBook(int id)
        {
            var dbBook = await _context.Books.FirstOrDefaultAsync(c => c.Id == id);
            var list = new List<GivingBookViewModel>();
            foreach (var reader in _context.Readers)
            {
                list.Add(new GivingBookViewModel(dbBook, reader));
            }

            return View(list);
        }
        
        public async Task<IActionResult> GiveBookForReader(int BookId, int ReaderId)
        {
            BookIssue issue = new()
            {
                BookID = BookId,
                ReaderId = ReaderId,
                IssueDate = DateTime.Now
            };
            _context.Add(issue);
            _context.Books.FirstOrDefault(c => c.Id == BookId).Count--;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(IssuedBooks));
        }
        public async Task<IActionResult> Details(int id)
        {
            var dbBook = await _context.Books.FirstOrDefaultAsync(c => c.Id == id);

            return View(dbBook);
        }
        public async Task<IActionResult> BookSearch(string name)
        {
            var allbooks = await _context.Books.Where(c => c.Name.Contains(name)).ToListAsync();

            return View(allbooks);
        }
    }
}

Controllers/ReadersController.cs
using LibraryApi.Data;
using LibraryApi.Models;
using LibraryApi.Models.VIewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryApi.Controllers
{
    public class ReadersController : Controller
    {
        private readonly LibraryContext _context;
        public ReadersController(LibraryContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Readers.ToListAsync());
        }
        public IActionResult AddReader()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddReader([Bind("FullName,Birthday")] Reader reader)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reader);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> DeleteReader(int id)
        {
            var reader = await _context.Readers.FirstOrDefaultAsync(c => c.Id == id);
            if (reader != null)
            {
                _context.Remove(reader);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var reader = await _context.Readers.FirstOrDefaultAsync(c => c.Id == id);
            if (reader == null)
            {
                return NotFound();
            }
            return View(reader);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Author,ReleaseDate")] Reader reader)
        {
            if (ModelState.IsValid)
            {
                var dbReader = _context.Readers.FirstOrDefault(c => c.Id == id);
                dbReader.FullName = reader.FullName;
                dbReader.Birthday = reader.Birthday;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> FullInfo(int id)
        {
            var reader = await _context.Readers.FirstOrDefaultAsync(c => c.Id == id);
            var booksId = _context.BookIssues.Where(c => c.ReaderId == reader.Id
            && c.ReturnDate == null).Select(c => c.BookID);
            var readerBooks = _context.Books.Where(c => booksId.Contains(c.Id));

            ReaderViewModel model = new(reader, readerBooks);
            return View(model);
        }
        public async Task<IActionResult> ReaderSearch(string name)
        {
            var readers = await _context.Readers.Where(c => c.FullName.Contains(name)).ToListAsync();

            return View(readers);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetLibrary</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Available Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="IssuedBooks">Issued Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Readers" asp-action="Index">Readers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>